define(["app","require"],function(app,require){
    //配置路由
    app.config(["$routeProvider","$controllerProvider",function($routeProvider,$controllerProvider){
        $routeProvider.when("/home",{
            templateUrl:"home.html",
            controller:"homeCtrl",
            resolve:{
                home: loadController({
                    url:"../javascripts/dest/controller/home.js",
                    name:"homeCtrl",
                    inject:["$scope","$rootScope","$http","Tool","Ajax","Weixin"],   
                },$controllerProvider)
            }
        }).when("/doctor",{
            templateUrl:"doctor.html",
            controller:"doctorCtrl",
            resolve:{
                doctor: loadController({
                    url:"../javascripts/dest/controller/doctor.js",
                    name:"doctorCtrl",
                    inject:["$scope","$rootScope","$http","Tool","Ajax","Params"],   
                },$controllerProvider)
            }
        }).when("/doctor/askDoctor",{
            templateUrl:"askdoctor.html",
            controller:"askDoctorCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/askDoctor.js",
                    name:"askDoctorCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/doctor/detail",{
            templateUrl:"doctordetail.html",
            controller:"doctorDetailCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/doctorDetail.js",
                    name:"doctorDetailCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/interaction",{
            templateUrl:"interaction.html",
            controller:"interactionCtrl",
            resolve:{
                interaction: loadController({
                    url:"../javascripts/dest/controller/interaction.js",
                    name:"interactionCtrl",
                    inject:["$scope","$rootScope","$http","Tool","Ajax"],   
                },$controllerProvider)
            }
        }).when("/interaction/detail",{
            templateUrl:"interactiondetail.html",
            controller:"interactionDetailCtrl",
            resolve:{
                interaction: loadController({
                    url:"../javascripts/dest/controller/interactionDetail.js",
                    name:"interactionDetailCtrl",
                    inject:["$scope","$rootScope","$http","Tool","Ajax"],   
                },$controllerProvider)
            }
        }).when("/user",{
            templateUrl:"user.html",
            controller:"userCtrl",
            resolve:{
                interaction: loadController({
                    url:"../javascripts/dest/controller/user.js",
                    name:"userCtrl",
                    inject:["$scope","Tool","Ajax"],   
                },$controllerProvider)
            }
        }).when("/user/userinfo",{
            templateUrl:"userinfo.html",
            controller:"userInfoCtrl",
            resolve:{
                userinfo:loadController({
                    url:"../javascripts/dest/controller/userInfo.js",
                    name:"userInfoCtrl",
                    inject:["$scope","$rootScope","Tool"],   
                },$controllerProvider)
            }
        }).when("/user/cush",{
            templateUrl:"cush.html",
            controller:"cushCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/cush.js",
                    name:"cushCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/user/cushover",{
            templateUrl:"cushover.html",
            controller:"cushOverCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/cushOver.js",
                    name:"cushOverCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/user/userinfochange",{
            templateUrl:"userinfochange.html",
            controller:"userInfoChangeCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/userInfoChange.js",
                    name:"userInfoChangeCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/activity",{
            templateUrl:"activity.html",
            controller:"activityCtrl",
            resolve:{
                activity:loadController({
                    url:"../javascripts/dest/controller/activity.js",
                    name:"activityCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],   
                },$controllerProvider)
            }
        }).when("/product/detail",{
            templateUrl:"productdetail.html",
            controller:"productDetailCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/productDetail.js",
                    name:"productDetailCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/product",{
            templateUrl:"product.html",
            controller:"productCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/product.js",
                    name:"productCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/exam/detail",{
            templateUrl:"examdetail.html",
            controller:"examDetailCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/examDetail.js",
                    name:"examDetailCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/discount",{
            templateUrl:"discount.html",
            controller:"discountCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/discount.js",
                    name:"discountCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/findpwd/phone",{
            templateUrl:"findpwdphone.html",
            controller:"findPassCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/findPass.js",
                    name:"findPassCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/findpwd/code",{
            templateUrl:"findpwdcode.html",
            controller:"findPassCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/findpass.js",
                    name:"findPassCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/findpwd/pwd",{
            templateUrl:"findpwdpwd.html",
            controller:"findPassCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/findpass.js",
                    name:"findPassCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/grab",{
            templateUrl:"grab.html",
            controller:"grabCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/grab.js",
                    name:"grabCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/grab/code",{
            templateUrl:"grabcode.html",
            controller:"grabCodeCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/grabCode.js",
                    name:"grabCodeCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/grab/order",{
            templateUrl:"graborder.html",
            controller:"grabOrderCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/grabOrder.js",
                    name:"grabOrderCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/login",{
            templateUrl:"login.html",
            controller:"loginCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/login.js",
                    name:"loginCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/makeorder",{
            templateUrl:"makeorder.html",
            controller:"makeOrderCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/makeOrder.js",
                    name:"makeOrderCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/news",{
            templateUrl:"news.html",
            controller:"newsCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/news.js",
                    name:"newsCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/news/detail",{
            templateUrl:"newsdetail.html",
            controller:"newsCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/news.js",
                    name:"newsCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/order",{
            templateUrl:"order.html",
            controller:"orderCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/order.js",
                    name:"orderCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/pay",{
            templateUrl:"pay.html",
            controller:"payCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/pay.js",
                    name:"payCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/pay/result",{
            templateUrl:"payresult.html",
            controller:"payResultCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/payResult.js",
                    name:"payResultCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).when("/register",{
            templateUrl:"register.html",
            controller:"registerCtrl",
            resolve:{
                askDoctor:loadController({
                    url:"../javascripts/dest/controller/register.js",
                    name:"registerCtrl",
                    inject:["$scope","$rootScope","$http","Tool"],
                },$controllerProvider)
            }
        }).otherwise({redirectTo:"/home"})
    }])

    //将require的控制器注册到Module中
    function loadController(obj,$controllerProvider){
        return function($q){
            var deferred = $q.defer();
            require([obj.url],function(controller){
                controller.$inject = obj.inject;
                $controllerProvider.register(obj.name,controller);
                deferred.resolve();
            })
            return deferred.promise;
        }
    }
})