var express = require("express");
var routes = express();
var bodyParsers = require("body-parser");
routes.use(bodyParsers.json());
routes.use(bodyParsers.urlencoded({ extended: true }));

var loginSuccess = {
    "data":{
        "id":12391,
        "username":"18620369802",
        "phone":"18620369802",
        "birthday":852048000000,
        "realname":"刘玉成",
        "gender":null,
        "device":null,
        "password":null,
        "accessToken":"db284606729f481fb48d7bdbb373231b",
        "remark":null,
        "giftCode":1,
        "face":"djfajeia/afeafa/abc.jpg",
        "nickname":"hehe",
        "sex":"男",
        "openid":null,
        "age":20
    },
    "code":0,
    "message":"成功"
}
var loginError = {
    "data":null,
    "code":1,
    "message":"密码不正确"
}
var changeSuccess = {
    "data":{
        "id":null,
        "username":"18620369802",
        "phone":"18620369802",
        "birthday":-2303625600000,
        "realname":"刘玉成",
        "gender":null,
        "device":null,
        "password":null,
        "accessToken":"4f884a60062940cda7484fdaf8f2af3f",
        "remark":null,
        "giftCode":1,
        "face":null,
        "nickname":"小绿皮",
        "sex":"女",
        "openid":null,
        "age":26
    },
    "code":0,
    "message":"成功"
}
var orderSuccess = {
    "data": [
        {
            "id": 343,
            "orderNo": "201605101135214548",
            "hospitalId": 10088,
            "hospitalName": "加德美口腔南山区卓越维港店",
            "hospitalRegisterName": null,
            "professionName": null,
            "professionId": 20,
            "typeKey": "DENTAL",
            "doctorId": 10332,
            "doctorName": "林园哲",
            "productId": 10966,
            "productName": "超声波洁牙+抛光",
            "patient": "123",
            "hospitalAddr": "南山区卓越维港名苑9-13栋裙楼1-27",
            "treatmenttime": 1462935600000,
            "orderSource": 1,
            "patientTelephone": "18989899898",
            "hospitalTelephone": "0755-86399009",
            "sex": "男",
            "originalprice": 500,
            "discountprice": 450,
            "finalprice": null,
            "dealMoney": 50,
            "payMoney": 400,
            "giftMoney": 50,
            "scheduleId": 77592,
            "vistorId": 12391,
            "usertype": 4,
            "status": 4,
            "createtime": 1462851321000,
            "giftCodeId": null,
            "description": null,
            "permission": null,
            "finishtime": null,
            "code": null,
            "payStatus": 0,
            "alipaytradeno": null,
            "treatmenttimeStr": "2016-05-11",
            "createtimeStr": "2016-05-10"
        },
        {
            "id": 339,
            "orderNo": "201605041614497770",
            "hospitalId": 10088,
            "hospitalName": "加德美口腔南山区卓越维港店",
            "hospitalRegisterName": null,
            "professionName": null,
            "professionId": 64,
            "typeKey": "DENTAL",
            "doctorId": 10332,
            "doctorName": "林园哲",
            "productId": 10960,
            "productName": "牙齿矫正（美国隐适美隐型矫正）",
            "patient": "123",
            "hospitalAddr": "南山区卓越维港名苑9-13栋裙楼1-27",
            "treatmenttime": 1462419000000,
            "orderSource": 1,
            "patientTelephone": "18620369802",
            "hospitalTelephone": "0755-86399009",
            "sex": "男",
            "originalprice": 45000,
            "discountprice": 45000,
            "finalprice": null,
            "dealMoney": 9000,
            "payMoney": 36000,
            "giftMoney": 0,
            "scheduleId": 77595,
            "vistorId": 12391,
            "usertype": 4,
            "status": 4,
            "createtime": 1462349690000,
            "giftCodeId": null,
            "description": null,
            "permission": null,
            "finishtime": null,
            "code": null,
            "payStatus": 0,
            "alipaytradeno": null,
            "treatmenttimeStr": "2016-05-05",
            "createtimeStr": "2016-05-04"
        }
    ],
    "code": 0,
    "message": "成功"
}
var orderCancelSuccess = {
	"code":0
}
var orderCancelError = {
	"code":1
}
var cushSuccess = {
    "data": [
        {
            "id": 510553,
            "code": "K19811",
            "state": 2,
            "type": "",
            "relevancyGift": "",
            "effectDate": "2016-03-01",
            "endDate": "2016-06-30",
            "createTime": "2016-02-28 14:20:00.0",
            "flags": 300,
            "serialId": "7060300016",
            "money": 250,
            "userId": 12391
        },
		{
            "id": 510553,
            "code": "K19811",
            "state": 2,
            "type": "",
            "relevancyGift": "",
            "effectDate": "2016-03-01",
            "endDate": "2016-06-30",
            "createTime": "2016-02-28 14:20:00.0",
            "flags": 300,
            "serialId": "7060300016",
            "money": 300,
            "userId": 12391
        }
    ],
    "code": 0,
    "message": "成功"
}
var cushActiveSuccess = {
    "data": [
        {
            "id": 510553,
            "code": "K19811",
            "state": 2,
            "type": "",
            "relevancyGift": "",
            "effectDate": "2016-03-01",
            "endDate": "2016-06-30",
            "createTime": "2016-02-28 14:20:00.0",
            "flags": 300,
            "serialId": "7060300016",
            "money": 250,
            "userId": 12391
        }
    ],
    "code": 0,
    "message": "成功"
}
var cushOverSuccess = {
    "data": [
        {
            "id": 510553,
            "code": "K19811",
            "state": 1,
            "type": "",
            "relevancyGift": "",
            "effectDate": "2016-03-01",
            "endDate": "2016-06-30",
            "createTime": "2016-02-28 14:20:00.0",
            "flags": 300,
            "serialId": "7060300016",
            "money": 250,
            "userId": 12391
        },
		{
            "id": 510553,
            "code": "K19811",
            "state": 3,
            "type": "",
            "relevancyGift": "",
            "effectDate": "2016-03-01",
            "endDate": "2016-06-30",
            "createTime": "2016-02-28 14:20:00.0",
            "flags": 300,
            "serialId": "7060300016",
            "money": 300,
            "userId": 12391
        }
    ],
    "code": 0,
    "message": "成功"
}
var grabSuccess = [
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10086,
            "name":"童美口腔福田区金港豪庭店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1055",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10086,
        "id":10927,
        "introduction":null,
        "notice":null,
        "preferPrice":168,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":7,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10086/chaoshengboxiyapenshapaoguang/ae577a928a1e42e7804fbcfcff052f8c_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+喷砂+抛光",
        "amount":1
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10082,
            "name":"陈闯口腔车公庙劲松大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1052",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10082,
        "id":10892,
        "introduction":null,
        "notice":null,
        "preferPrice":200,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10082/chaoshengbojieyapaoguang/778c9c291069448db58ac0c5f9ff5fb0_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洁牙+抛光",
        "amount":0
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10080,
            "name":"利民口腔福民路瑞和园店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1051",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10080,
        "id":10876,
        "introduction":null,
        "notice":null,
        "preferPrice":160,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10080/chaoshengbojieyapaoguang/0feb132e47434dc990c293fe1d77b219_300X300.jpg",
        "specialty":"通用",
        "standPrice":200,
        "status":1,
        "title":"超声波洁牙+抛光",
        "amount":1
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10073,
            "name":"天美健齿科福田区上梅林梅华店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1047",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10073,
        "id":10807,
        "introduction":null,
        "notice":null,
        "preferPrice":128,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10073/chaoshengboxiyapenshapaoguang/e94c7927c259430f95e38912d53ceee0_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+喷砂+抛光",
        "amount":0
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10072,
            "name":"天美健齿科福田区梅林中康店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1046",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10072,
        "id":10794,
        "introduction":null,
        "notice":null,
        "preferPrice":128,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":9,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10072/chaoshengboxiyapenshapaoguang/3cffde240b88491880c1156f1d1afab9_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+喷砂+抛光",
        "amount":1
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10069,
            "name":"韦博口腔福田区新州家乐福店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1044",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10069,
        "id":10748,
        "introduction":null,
        "notice":null,
        "preferPrice":128,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10069/chaoshengboxiyapenshatuominpaoguang/5e6694e56db8437186cbb15b46138c31_300X300.jpg",
        "specialty":"通用",
        "standPrice":700,
        "status":1,
        "title":"超声波洗牙+喷砂+脱敏抛光",
        "amount":0
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10038,
            "name":"德益口腔福田区石厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1040",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10038,
        "id":10654,
        "introduction":null,
        "notice":null,
        "preferPrice":200,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":9,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10038/chaoshengboxiyapaoguang/0cfc3cbfb0f041f0a2fe3c0ac9d645c6.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+抛光",
        "amount":0
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10048,
            "name":"弘和齿科福田保税区桂花苑店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1039",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10048,
        "id":10621,
        "introduction":null,
        "notice":null,
        "preferPrice":150,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10048/chaoshengboxiyapaoguang/ce00f242abb947c2860410107e7d17ed_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+抛光",
        "amount":1
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10043,
            "name":"弘和齿科福田石厦阳光花园店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1034",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10043,
        "id":10559,
        "introduction":null,
        "notice":null,
        "preferPrice":150,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":9,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10043/chaoshengboxiyapaoguang/ad616fb3f017414aa85612156cd49ff2_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+抛光",
        "amount":0
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":20,
                "parentid":2,
                "name":"洗牙",
                "status":1,
                "description":"齿科->洗牙",
                "orderseq":2,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10042,
            "name":"弘和齿科福田区百花长安花园店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":null,
            "longitude":null,
            "telephone":null,
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":"DSZ1033",
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10042,
        "id":10547,
        "introduction":null,
        "notice":null,
        "preferPrice":150,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":7,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10042/chaoshengboxiyapaoguang/4e8cf01fe54a4e6cb4e2f082b97d975e_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"超声波洗牙+抛光",
        "amount":0
    }
]
var productSuccess = [
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10069,
            "name":"韦博口腔福田区新州家乐福店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.528336,
            "longitude":114.02539,
            "telephone":"0755-83213148",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10069,
        "id":10747,
        "introduction":"美国3Mz350纳米树脂Filtek™ Z350XT具有牙本质色、牙体色、牙釉质色和透明色，在临床充填修复过程中能更加逼真的恢复天然牙般的自然美学效果。新一代3M纳米树脂，与人体生物相容性好，患者牙体磨除量少，操作简单，成形准确。对于美观要求高，而又不愿磨除过多牙体组织的高端商务人士，美国3Mz350纳米树脂补牙是最佳的选择。",
        "notice":"",
        "preferPrice":99999,
        "pricetype":"元",
        "priceunit":"牙洞",
        "recommend":null,
        "sales":7,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10069/buyajinkounamishuzhi/462c25a9d05542c9b9c82e28b4fb972b_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"补牙(进口纳米树脂)",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10070,
            "name":"润和齿科福田区下沙岁宝店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.521578,
            "longitude":114.04444,
            "telephone":"0755-23603543",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10070,
        "id":10751,
        "introduction":"美国3Mz350纳米树脂Filtek™ Z350XT具有牙本质色、牙体色、牙釉质色和透明色，在临床充填修复过程中能更加逼真的恢复天然牙般的自然美学效果。新一代3M纳米树脂，与人体生物相容性好，患者牙体磨除量少，操作简单，成形准确。对于美观要求高，而又不愿磨除过多牙体组织的高端商务人士，美国3Mz350纳米树脂补牙是最佳的选择。",
        "notice":"",
        "preferPrice":99,
        "pricetype":"元",
        "priceunit":"牙洞",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10070/buyajinkounamishuzhi/4d4fea62dbcc4ed98483039f19f31345_300X300.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"补牙(进口纳米树脂)",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10008,
            "name":"博耀齿科罗湖区莲塘店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.561733,
            "longitude":114.16914,
            "telephone":"0755-25511416",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10008,
        "id":10338,
        "introduction":"龋病是一种由口腔中多种因素复合作用所导致的牙齿硬组织进行性病损，表现为无机质的脱矿和有机质的分解，随着病程的发展而有一色泽变化到形成实质性病损的演变过程充填术是目前治疗龋齿应用最广泛且成效较好的方法。 富士IX玻璃离子水门汀材料是一种快速固型玻璃离子修复材料，具有边缘密封性良好、防止继发龋、坚固美观等优点，适用于乳牙的充填。 ",
        "notice":"",
        "preferPrice":150,
        "pricetype":"元",
        "priceunit":"颗",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10008/quchixiufufushiixbolilizitianchong/f18121d2d3ef44bc8999e7a9a2197b62_300X300.jpg",
        "specialty":"通用",
        "standPrice":170,
        "status":1,
        "title":"龋齿修复（富士IX玻璃离子填充）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10022,
            "name":"赛亚齿科南山区创维大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.540735,
            "longitude":113.9447,
            "telephone":"0755-86562826",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10022,
        "id":10390,
        "introduction":"美国3Mz350纳米树脂Filtek™ Z350XT具有牙本质色、牙体色、牙釉质色和透明色，在临床充填修复过程中能更加逼真的恢复天然牙般的自然美学效果。新一代3M纳米树脂，与人体生物相容性好，患者牙体磨除量少，操作简单，成形准确。对于美观要求高，而又不愿磨除过多牙体组织的高端商务人士，美国3Mz350纳米树脂补牙是最佳的选择。",
        "notice":"",
        "preferPrice":190,
        "pricetype":"元起",
        "priceunit":"牙洞",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10022/buyajinkounamishuzhi/bc3d895a45654b8192434280895053c0.jpg",
        "specialty":"通用",
        "standPrice":200,
        "status":1,
        "title":"补牙（进口纳米树脂）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10023,
            "name":"赛亚齿科南山区科技南路滨福店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.524986,
            "longitude":113.94944,
            "telephone":"0755-86008809",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10023,
        "id":10405,
        "introduction":"美国3Mz350纳米树脂Filtek™ Z350XT具有牙本质色、牙体色、牙釉质色和透明色，在临床充填修复过程中能更加逼真的恢复天然牙般的自然美学效果。新一代3M纳米树脂，与人体生物相容性好，患者牙体磨除量少，操作简单，成形准确。对于美观要求高，而又不愿磨除过多牙体组织的高端商务人士，美国3Mz350纳米树脂补牙是最佳的选择。",
        "notice":"",
        "preferPrice":190,
        "pricetype":"元起",
        "priceunit":"牙洞",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10023/buyajinkounamishuzhi/784d82b1452645509b1311b5d2510e4f.jpg",
        "specialty":"通用",
        "standPrice":200,
        "status":1,
        "title":"补牙（进口纳米树脂）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10024,
            "name":"赛亚齿科南山区蛇口南水步行街店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.488298,
            "longitude":113.92204,
            "telephone":"0755-26686930",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10024,
        "id":10420,
        "introduction":"美国3Mz350纳米树脂Filtek™ Z350XT具有牙本质色、牙体色、牙釉质色和透明色，在临床充填修复过程中能更加逼真的恢复天然牙般的自然美学效果。新一代3M纳米树脂，与人体生物相容性好，患者牙体磨除量少，操作简单，成形准确。对于美观要求高，而又不愿磨除过多牙体组织的高端商务人士，美国3Mz350纳米树脂补牙是最佳的选择。",
        "notice":"",
        "preferPrice":190,
        "pricetype":"元起",
        "priceunit":"牙洞",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10024/buyajinkounamishuzhi/5f07b36528e6495a805258a9dfeddd4e.jpg",
        "specialty":"通用",
        "standPrice":200,
        "status":1,
        "title":"补牙（进口纳米树脂）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10085,
            "name":"童佳口腔罗湖区桂园路店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.547361,
            "longitude":114.113014,
            "telephone":"0755-25589948",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10085,
        "id":10908,
        "introduction":"GC纳米树脂是通过模仿周围牙体组织的散射和漫反射的光学效果，单一颜色就可以达到理想的变色龙效果，使整个临床操作过程更加简便。分前牙用和后牙两种复合树脂，前牙单支A3可覆盖传统VITA16色比色中的10个颜色，方便临床操作，具有出色的美学效果。后牙用复合树脂的设计充分考虑到后牙的功能性，具备理想的物理强度，同时还不会磨损对颌牙",
        "notice":"",
        "preferPrice":198,
        "pricetype":"元",
        "priceunit":"颗",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10085/buyaribengcnamishuzhi/574563aa1a93403aaa46adcbd7462a34_300X300.png",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"补牙（日本GC纳米树脂）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10086,
            "name":"童美口腔福田区金港豪庭店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.51866,
            "longitude":114.06421,
            "telephone":"0755-86686619",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10086,
        "id":10928,
        "introduction":"GC纳米树脂是通过模仿周围牙体组织的散射和漫反射的光学效果，单一颜色就可以达到理想的变色龙效果，使整个临床操作过程更加简便。分前牙用和后牙两种复合树脂，前牙单支A3可覆盖传统VITA16色比色中的10个颜色，方便临床操作，具有出色的美学效果。后牙用复合树脂的设计充分考虑到后牙的功能性，具备理想的物理强度，同时还不会磨损对颌牙",
        "notice":"",
        "preferPrice":198,
        "pricetype":"元",
        "priceunit":"颗",
        "recommend":null,
        "sales":8,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10086/buyaribengcnamishuzhi/c409f2e7bf964c8a8c6624c56f8a0286_300X300.png",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"补牙（日本GC纳米树脂）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10038,
            "name":"德益口腔福田区石厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.52405,
            "longitude":114.05681,
            "telephone":"0755-88301520",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10038,
        "id":10647,
        "introduction":"美国3Mz350纳米树脂Filtek™ Z350XT具有牙本质色、牙体色、牙釉质色和透明色，在临床充填修复过程中能更加逼真的恢复天然牙般的自然美学效果。新一代3M纳米树脂，与人体生物相容性好，患者牙体磨除量少，操作简单，成形准确。对于美观要求高，而又不愿磨除过多牙体组织的高端商务人士，美国3Mz350纳米树脂补牙是最佳的选择。",
        "notice":"",
        "preferPrice":234,
        "pricetype":"元起",
        "priceunit":"颗",
        "recommend":null,
        "sales":7,
        "sequence":null,
        "smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10038/buyameiguo3mnamishuzhitianchong/199d145b275c40b88b1fe791427f7950.jpg",
        "specialty":"通用",
        "standPrice":260,
        "status":1,
        "title":"补牙(美国3M纳米树脂填充)",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":2,
                "parentid":1,
                "name":"牙科",
                "status":1,
                "description":"牙科",
                "orderseq":1,
                "level":1,
                "typekey":"DENTAL",
                "childList":null
            },
            "subProfession":{
                "id":22,
                "parentid":2,
                "name":"补牙",
                "status":1,
                "description":"齿科->补牙",
                "orderseq":4,
                "level":2,
                "typekey":"DENTAL",
                "childList":null
            }
        },
        "daydate":null,
        "discount":null,
        "discountId":null,
        "hospital":{
            "id":10080,
            "name":"利民口腔福民路瑞和园店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.523588,
            "longitude":114.055916,
            "telephone":"0755-83494939",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10080,
        "id":10864,
        "introduction":"",
        "notice":"",
        "preferPrice":240,
        "pricetype":"元",
        "priceunit":"颗",
        "recommend":null,
        "sales":9,
        "sequence":null,
        "smallImg":null,
		"smallImg":"http://biz.uokang.com/upload/image/hospital/dental/10038/buyameiguo3mnamishuzhitianchong/199d145b275c40b88b1fe791427f7950.jpg",
        "specialty":"通用",
        "standPrice":300,
        "status":1,
        "title":"补牙（瑞士瓷化树脂）",
        "amount":null
    }
]
var giftCheck = {
	result:0
}
var giftSuccess = {
	data:{
		"id":773,
	    "username":"123",
	    "mobile":"18620369802",
	    "daydate":"2016-05-17",
	    "giftCode":"2016D1057SZ0517",
	    "status":0,
	    "hospitalAddress":"深圳市南山区蛇口兴华路9号海上世界海滨商业大厦4001",
	    "hospitalName":"深圳市吾华口腔",
	    "productName":"全套洗牙(超声波+喷砂+抛光)",
	    "createtime":"2016-05-16",
	    "userId":12391
	},
	code:0

}
var findSuccess = "y";

var examSuccess = [
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":8.7,
        "discountId":null,
        "hospital":{
            "id":10020,
            "name":"中信体检福田区NEO大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.54217,
            "longitude":114.088844,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10020,
        "id":10283,
        "introduction":"适用人群： 1、有心脑血管疾病家族史；患有冠心病、高血压、高脂血症、糖尿病者；2、45岁以上、肥胖者；长期吸烟、高脂饮食、缺乏体育运动者；3、活动后和静息状态下胸闷、心悸者；长期头晕者。 套餐说明：1、用于年内专项病体检及复查；2、在大套餐的基础上加项参考用；",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超在月经干净7天后检查；3、”★“为空腹项目，“ ※“为需要留尿便项目；4、体内有磁性金属异物者、妊娠三个月内者请勿进行核磁检查；5、以上价格，可能会有浮动，请以最终体检中心结算价为准。",
        "preferPrice":2857,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":10,
        "sequence":null,
        "smallImg":null,
        "specialty":"通用",
        "standPrice":3285,
        "status":1,
        "title":"心脑血管筛查套餐",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":8.2,
        "discountId":null,
        "hospital":{
            "id":10020,
            "name":"中信体检福田区NEO大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.54217,
            "longitude":114.088844,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10020,
        "id":10280,
        "introduction":"适用人群：有肝病家族史。与肝病患者有亲密接触，以前患有或现在患有肝炎者；有外伤输血史、静脉内主色吸毒史、使用未经严格消毒的器具者；有肝区不适。左肋部隐痛、胀痛、刺痛或灼热感，皮肤，小便发黄等症状者；经常在公共场所饮食，有多个性伴侣及肥胖人群。 套餐说明：1、用于年内专项病体检及复查；2、在大套餐的基础上加项参考用；",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超在月经干净7天后检查；3、“★”为空腹项目，“ ※”为需要留尿便项目；4、以上价格，可能会有浮动，请以最终体检中心结算价为准。",
        "preferPrice":1970,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":10,
        "sequence":null,
        "smallImg":null,
        "specialty":"通用",
        "standPrice":2403,
        "status":1,
        "title":"肝脏筛查套餐",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":6.1,
        "discountId":null,
        "hospital":{
            "id":10020,
            "name":"中信体检福田区NEO大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.54217,
            "longitude":114.088844,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10020,
        "id":10286,
        "introduction":"特别适用于以下人群 ①吸烟/喝酒人群；②家族中有癌症患者；③高危工作人群和地方性肿瘤高发人群及在常规体检中发现肿块或阴影的人群。",
        "notice":"本项目得到平安保险公司承保,最高赔付达100万元人民币,客户需提前三天预约,详情咨询中信健康体检中心健康顾问黄先生13510697029",
        "preferPrice":11876,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":2,
        "sequence":null,
        "smallImg":null,
        "specialty":"男",
        "standPrice":19470,
        "status":1,
        "title":"男性五癌preMiD肿瘤超早期检测",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":8.8,
        "discountId":null,
        "hospital":{
            "id":10020,
            "name":"中信体检福田区NEO大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.54217,
            "longitude":114.088844,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10020,
        "id":10294,
        "introduction":"主要适用于以下人群①吸烟人群。②家族中是否有癌症患者，如果有则需及早开始防癌检查。③心理或情绪长期压抑的人群。④患有与癌症密切相关的感染性疾病，比如乙肝、丙肝、EB病毒(人类疱疹病毒)、人乳头状瘤病毒等。⑤其他不良生活习惯人群。如嗜烟酒、很少运动、喜爱高脂肪和高糖饮食、肥胖等。",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超、钼钯在月经干净7天后检查；3、乳腺彩超、乳腺钼钯可二选一，也可同时检查；4、“★”为空腹项目，“※”为需要留尿便项目；5、体内有磁性金属异物者、妊娠三个月内者请勿进行核磁检查；6、以上价格，可能会有浮动，请以最终订单结算价为准。",
        "preferPrice":4259,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":9,
        "sequence":null,
        "smallImg":null,
        "specialty":"女",
        "standPrice":4840,
        "status":1,
        "title":"肿瘤相关（高档）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":8.1,
        "discountId":null,
        "hospital":{
            "id":10019,
            "name":"中信体检南山区蛇口中心路店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.499205,
            "longitude":113.941025,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10019,
        "id":10232,
        "introduction":" 注重常规与心血管、肿瘤早期检测同时为客户提供疾病风险评估、制定健康规划等综合性健康指导，共计52项。",
        "notice":"1、“★”为空腹项目，“※”为需要留尿便项目；2、体内有磁性金属异物者、妊娠三个月内者请勿进行核磁检查；3、以上价格，可能会有浮动，请以最终订单结算价为准。",
        "preferPrice":2780,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":7,
        "sequence":null,
        "smallImg":null,
        "specialty":"男",
        "standPrice":3427,
        "status":1,
        "title":"成功人士、亚健康人群高档套餐",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":5.9,
        "discountId":null,
        "hospital":{
            "id":10019,
            "name":"中信体检南山区蛇口中心路店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.499205,
            "longitude":113.941025,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10019,
        "id":10225,
        "introduction":"在常规体检的基础上增加了常见肿瘤筛查等，共计33项。",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超在月经干净7天后检查；3、“★”为空腹项目，“※”为需要留尿便项目；4、以上价格，可能会有浮动，请以最终体检中心结算价为准。",
        "preferPrice":746,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":5,
        "sequence":null,
        "smallImg":null,
        "specialty":"女",
        "standPrice":1271,
        "status":1,
        "title":"30-40岁人群标准套餐",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":5,
        "discountId":null,
        "hospital":{
            "id":10020,
            "name":"中信体检福田区NEO大厦店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.54217,
            "longitude":114.088844,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10020,
        "id":10261,
        "introduction":"适用人群：30岁以下人群。 包含临床常规检查、各类实验室及影像学基础检查，适合想了解自身基础状况的人群",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超在月经干净7天后检查；3、”★“为空腹项目，“ ※“为需要留尿便项目；4、以上价格，可能会有浮动，请以最终体检中心结算价为准。",
        "preferPrice":500,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":null,
        "specialty":"女",
        "standPrice":1001,
        "status":1,
        "title":"30岁以下人群标准套餐",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":8.5,
        "discountId":null,
        "hospital":{
            "id":10019,
            "name":"中信体检南山区蛇口中心路店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.499205,
            "longitude":113.941025,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10019,
        "id":10237,
        "introduction":" 独家引进头部核磁，早期筛查脑颈部血管、颈椎病变，同时为客户提供疾病风险评估、制定健康规划等综合性健康指导，共计82项。",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超在月经干净7天后检查；3、“★”为空腹项目，“※”为需要留尿便项目；4、体内有磁性金属异物者、妊娠三个月内者请勿进行核磁检查；5、以上价格，可能会有浮动，请以最终订单结算价为准。",
        "preferPrice":9030,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":2,
        "sequence":null,
        "smallImg":null,
        "specialty":"女",
        "standPrice":10600,
        "status":1,
        "title":"望族企业家套餐",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":67,
                "parentid":5,
                "name":"常规体检",
                "status":1,
                "description":"体检->常规体检",
                "orderseq":2,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":8.8,
        "discountId":null,
        "hospital":{
            "id":10019,
            "name":"中信体检南山区蛇口中心路店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.499205,
            "longitude":113.941025,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10019,
        "id":10256,
        "introduction":"适用人群：①吸烟人群。②家族中是否有癌症患者，如果有则需及早开始防癌检查。③心理或情绪长期压抑的人群。④患有与癌症密切相关的感染性疾病，比如乙肝、丙肝、EB病毒(人类疱疹病毒)、人乳头状瘤病毒等。⑤其他不良生活习惯人群。如嗜烟酒、很少运动、喜爱高脂肪和高糖饮食、肥胖等。",
        "notice":"1、女性在月经干净3-5天后进行妇科检查；2、乳腺彩超、钼钯在月经干净7天后检查；3、乳腺彩超、乳腺钼钯可二选一，也可同时检查；4、“★”为空腹项目，“※”为需要留尿便项目；5、体内有磁性金属异物者、妊娠三个月内者请勿进行核磁检查；6、以上价格，可能会有浮动，请以最终订单结算价为准。",
        "preferPrice":4260,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":6,
        "sequence":null,
        "smallImg":null,
        "specialty":"女",
        "standPrice":4840,
        "status":1,
        "title":"肿瘤相关（高档）",
        "amount":null
    },
    {
        "applyPerson":null,
        "category":{
            "profession":{
                "id":5,
                "parentid":1,
                "name":"体检",
                "status":1,
                "description":"体检科",
                "orderseq":4,
                "level":1,
                "typekey":"EXAMINATION",
                "childList":null
            },
            "subProfession":{
                "id":72,
                "parentid":5,
                "name":"孕前体检",
                "status":1,
                "description":"体检->孕前体检",
                "orderseq":6,
                "level":2,
                "typekey":"EXAMINATION",
                "childList":null
            }
        },
        "daydate":null,
        "discount":7.9,
        "discountId":null,
        "hospital":{
            "id":10019,
            "name":"中信体检南山区蛇口中心路店",
            "address":null,
            "description":null,
            "logo":null,
            "latitude":22.499205,
            "longitude":113.941025,
            "telephone":"400-6626-888",
            "city":null,
            "area":null,
            "status":null,
            "createtime":null,
            "score":null,
            "commentnum":null,
            "code":null,
            "enterpriseId":null,
            "registerName":null,
            "distance":null
        },
        "hospitalId":10019,
        "id":10239,
        "introduction":"适用人群：孕龄女性、肥胖女性、年龄≥30岁女性、白领亚健康人群；有遗传疾病家族史，肿瘤病史，近亲结婚的人群，有不良孕产史的女性。有不良生活习惯、工作生活中接触不良因素如放射性物质的人群。",
        "notice":"1、孕前检查可以及早发现妇科疾病、传染病及遗传性疾病，及时进行有效的预防和治疗，孕前检查是优生优育的基础。2、女性在月经干净3-5天后进行妇科检查；3、乳腺彩超在月经干净7天后检查；4、”★“为空腹项目，“ ※“为需要留尿便项目；5、以上价格，可能会有浮动，请以最终体检中心结算价为准。",
        "preferPrice":3393,
        "pricetype":"元",
        "priceunit":"次",
        "recommend":null,
        "sales":9,
        "sequence":null,
        "smallImg":null,
        "specialty":"女",
        "standPrice":4295,
        "status":1,
        "title":"孕育前体检套餐",
        "amount":null
    }
]

var examHosSuccess = {
    "pageRows":10,
    "currentPage":0,
    "list":[
        {
            "id":10019,
            "name":"中信体检南山区蛇口中心路店",
            "address":"南山区蛇口中心路致远大厦B座",
            "description":" 中信健康秉持“深度体检，广度健康管理”的理念，遵循“以客户为中心，以市场为导向”的原则，依托优雅的体检环境，一流的专家团队、尖端的医检设备、人性化的服务流程、科学的健康管理体系，整合全国知名医院，提供集健康体检与诊断、健康咨询与教育、健康管理与保障、疾病干预与管理等三维立体的健康管理服务！ 中信体检南山中心经营面积近4000平方米，位于南山区后海商圈致远大厦内，东临深圳湾口岸、西靠后海商业中心，距地铁口500 米，交通便捷。采用欧美式风格布局，环境优雅、设备精良，设有影像中心、高级VIP 套房、名中医馆、抗衰老中心、多媒体功能厅等，可满足各类精英人士的健康检查及健康保养需求。",
            "logo":"http://biz.uokang.com/upload/image/hospital/logo/zhongxintijiannanshanzhongxinludian/193042349.jpg",
            "latitude":22.499205,
            "longitude":113.941025,
            "telephone":"400-6626-888",
            "city":"深圳",
            "area":"南山区",
            "status":null,
            "createtime":1445599842000,
            "score":null,
            "commentnum":null,
            "code":"ESZ1001",
            "enterpriseId":null,
            "registerName":"深圳中信致远门诊部分公司",
            "distance":null
        },
        {
            "id":10020,
            "name":"中信体检福田区NEO大厦店",
            "address":"福田区深南中路6011号NEO大厦A座16层",
            "description":" 中信健康秉持“深度体检，广度健康管理”的理念，遵循“以客户为中心，以市场为导向”的原则，依托优雅的体检环境，一流的专家团队、尖端的医检设备、人性化的服务流程、科学的健康管理体系，整合全国知名医院，提供集健康体检与诊断、健康咨询与教育、健康管理与保障、疾病干预与管理等三维立体的健康管理服务！ 中信体检福田中心设在深南大道与香蜜湖路交接处的地标建筑-国际商务综合体NEO大厦内，营业总面积2000平方米。上接北环、滨海、广深高速，下通1号地铁线，置身深圳金融、物流总部交汇处，毗邻香蜜湖高级住宅群和高尔夫会所、五星酒店、高级餐厅。",
            "logo":"http://biz.uokang.com/upload/image/hospital/logo/zhongxintijianfutianlvjingjiyuandashadian/193248626.jpg",
            "latitude":22.54217,
            "longitude":114.088844,
            "telephone":"400-6626-888",
            "city":"深圳",
            "area":"福田区",
            "status":null,
            "createtime":1445599969000,
            "score":null,
            "commentnum":null,
            "code":"ESZ1002",
            "enterpriseId":null,
            "registerName":"深圳中信门诊部分公司",
            "distance":null
        }
    ],
    "startIndex":-10
}

var doctorSche = {
    "data":[
        {
            "date":"2016-06-09",
            "dateStr":"2016-06-09",
            "weekDay":"星期四",
            "timeList":[
                {
                    "scheduleid":39614,
                    "doctorid":null,
                    "date":"2016-06-09 09:00",
                    "starttime":"09:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39615,
                    "doctorid":null,
                    "date":"2016-06-09 09:30",
                    "starttime":"09:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39616,
                    "doctorid":null,
                    "date":"2016-06-09 10:00",
                    "starttime":"10:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39617,
                    "doctorid":null,
                    "date":"2016-06-09 10:30",
                    "starttime":"10:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39618,
                    "doctorid":null,
                    "date":"2016-06-09 11:00",
                    "starttime":"11:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39619,
                    "doctorid":null,
                    "date":"2016-06-09 11:30",
                    "starttime":"11:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39620,
                    "doctorid":null,
                    "date":"2016-06-09 14:00",
                    "starttime":"14:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39621,
                    "doctorid":null,
                    "date":"2016-06-09 14:30",
                    "starttime":"14:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39623,
                    "doctorid":null,
                    "date":"2016-06-09 15:00",
                    "starttime":"15:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39625,
                    "doctorid":null,
                    "date":"2016-06-09 15:30",
                    "starttime":"15:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39626,
                    "doctorid":null,
                    "date":"2016-06-09 16:00",
                    "starttime":"16:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39628,
                    "doctorid":null,
                    "date":"2016-06-09 16:30",
                    "starttime":"16:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                }
            ],
            "scheduleid":39628
        },
        {
            "date":"2016-06-10",
            "dateStr":"2016-06-10",
            "weekDay":"星期五",
            "timeList":[
                {
                    "scheduleid":39622,
                    "doctorid":null,
                    "date":"2016-06-10 14:30",
                    "starttime":"14:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39624,
                    "doctorid":null,
                    "date":"2016-06-10 15:00",
                    "starttime":"15:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39627,
                    "doctorid":null,
                    "date":"2016-06-10 16:00",
                    "starttime":"16:00",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                },
                {
                    "scheduleid":39629,
                    "doctorid":null,
                    "date":"2016-06-10 16:30",
                    "starttime":"16:30",
                    "endtime":null,
                    "checked":false,
                    "numberLimit":null,
                    "remain":null,
                    "hospitalId":null
                }
            ],
            "scheduleid":39629
        },
		{
			"date":"2016-06-11",
			"dateStr":"2016-06-09",
			"weekDay":"星期四",
			"timeList":[
				{
					"scheduleid":39614,
					"doctorid":null,
					"date":"2016-06-09 09:00",
					"starttime":"09:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39615,
					"doctorid":null,
					"date":"2016-06-09 09:30",
					"starttime":"09:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39616,
					"doctorid":null,
					"date":"2016-06-09 10:00",
					"starttime":"10:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39617,
					"doctorid":null,
					"date":"2016-06-09 10:30",
					"starttime":"10:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39618,
					"doctorid":null,
					"date":"2016-06-09 11:00",
					"starttime":"11:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39619,
					"doctorid":null,
					"date":"2016-06-09 11:30",
					"starttime":"11:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39620,
					"doctorid":null,
					"date":"2016-06-09 14:00",
					"starttime":"14:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39621,
					"doctorid":null,
					"date":"2016-06-09 14:30",
					"starttime":"14:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39623,
					"doctorid":null,
					"date":"2016-06-09 15:00",
					"starttime":"15:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39625,
					"doctorid":null,
					"date":"2016-06-09 15:30",
					"starttime":"15:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39626,
					"doctorid":null,
					"date":"2016-06-09 16:00",
					"starttime":"16:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39628,
					"doctorid":null,
					"date":"2016-06-09 16:30",
					"starttime":"16:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				}
			],
			"scheduleid":39628
		},
		{
			"date":"2016-06-12",
			"dateStr":"2016-06-10",
			"weekDay":"星期五",
			"timeList":[
				{
					"scheduleid":39622,
					"doctorid":null,
					"date":"2016-06-10 14:30",
					"starttime":"14:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39624,
					"doctorid":null,
					"date":"2016-06-10 15:00",
					"starttime":"15:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39627,
					"doctorid":null,
					"date":"2016-06-10 16:00",
					"starttime":"16:00",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				},
				{
					"scheduleid":39629,
					"doctorid":null,
					"date":"2016-06-10 16:30",
					"starttime":"16:30",
					"endtime":null,
					"checked":false,
					"numberLimit":null,
					"remain":null,
					"hospitalId":null
				}
			],
			"scheduleid":39629
		}

	],
    "code":0,
    "message":"成功"
}

routes.post("/wx/login/wxlogin",function(req,res){
    var userName = req.body.phone;
    var password = req.body.password;
    if(userName=="18124792560"&password=="uokang123"){
        res.json(loginSuccess);
    }else{
        res.json(loginError);
    }
	res.end();
})
routes.post("/wx/mycount/updateUserInfo",function(req,res){
    var name = req.body.name;
    var val = req.body.val;
    if(name=="sex"&val=="男"){
        res.json(changeSuccess);
    }else{
        res.json(loginError);
    }
	res.end();
})
routes.post("/wx/order/queryOrderList",function(req,res){
	res.json(orderSuccess);
	res.end();
})

routes.post("/wx/order/orderCacel",function(req,res){
	res.json(orderCancelSuccess);
	res.end();
})

routes.post("/wx/order/findAllVouchers",function(req,res){
	res.json(cushSuccess);
	res.end();
})

routes.post("/wx/order/activate",function(req,res){
	res.json(cushActiveSuccess);
	res.end();
})
routes.post("/wx/order/overdue",function(req,res){
	res.json(cushOverSuccess);
	res.end();
})
routes.post("/wx/gift/queryproduct",function(req,res){
	var page = req.body.currentPage;
	res.json(grabSuccess);
	res.end();
})
routes.post("/wx/product/querylist",function(req,res){
	var profression = req.body.professionId;
	var currentPage = req.body.currentPage;
	if(currentPage<3){
		if(profression==5){
			res.json(examSuccess);
		}else{
			res.json(productSuccess);
		}
	}else{
		var empty = [];
		res.json(empty);
	}
	res.end();
})
routes.post("/wx/gift/getgiftproduct",function(req,res){
	res.json(giftSuccess);
	res.end();
})
routes.post("/wx/order/checkCode",function(req,res){
	res.json(giftCheck);
	res.end();
})
routes.post("/wx/gift/getgiftproduct",function(req,res){
	res.json(giftSuccess);
	res.end();
})
routes.post("/wx/findpass/findPassPhontCheck",function(req,res){
	res.send(findSuccess);
	res.end();
})
routes.post("/wx/hospital/querylist",function(req,res){
	res.send(examHosSuccess);
	res.end();
})

routes.post("/weixin/check/getjsconfig",function(req,res){
	res.send(examHosSuccess);
	res.end();
})

routes.post("/wx/order/querybydoctorid",function(req,res){
	res.send(doctorSche);
	res.end();
})






module.exports = routes;
